### ISSUE TITLE
师傅，java8和java15环境都运行不了

### ISSUE THREAD

**Issue by little-boy1** [errors11/TomcatVuln#3]

**Comment by errors11** [comment]
java8可以的

**Comment by Songs-YZS** [comment]
师傅，java8会报错：java -jar TomcatVuln-1.0-SNAPSHOT.jar
四月 25, 2024 5:40:35 下午 javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 16 by JavaFX runtime of version 8.0.121
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javafx.fxml.LoadException:
file:/C:/Users/15317/Desktop/code(1)/TomcatVuln-1.0-SNAPSHOT/TomcatVuln-1.0-SNAPSHOT.jar!/views/MainMenu.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
        at org.dudu.TomcatVuln.TomcatAttackMain.start(TomcatAttackMain.java:17)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        ... 1 more
Caused by: java.lang.RuntimeException: org.dom4j.DocumentException: 1 字节的 UTF-8 序列的字节 1 无效。
        at org.dudu.TomcatVuln.view.MainMenuView.initialize(MainMenuView.java:249)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        ... 17 more
Caused by: org.dom4j.DocumentException: 1 字节的 UTF-8 序列的字节 1 无效。
        at org.dom4j.io.SAXReader.read(SAXReader.java:513)
        at org.dom4j.io.SAXReader.read(SAXReader.java:325)
        at org.dudu.TomcatVuln.utils.FileUtil.writeConfig(FileUtil.java:78)
        at org.dudu.TomcatVuln.view.MainMenuView.initialize(MainMenuView.java:233)
        ... 18 more
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 1 字节的 UTF-8 序列的字节 1 无效。
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at org.dom4j.io.SAXReader.read(SAXReader.java:494)
        ... 21 more
Exception running application org.dudu.TomcatVuln.TomcatAttackMain

**Comment by errors11** [comment]
解决办法：使用记事本打开该XML文件，另存为，编码选择UTF-8。你试一下用这个改改config.xml

**Comment by yzdlkxkl** [comment]
> 师傅，java8会报错：java -jar TomcatVuln-1.0-SNAPSHOT.jar 四月 25, 2024 5:40:35 下午 javafx.fxml.FXMLLoader$ValueElement processValue WARNING: Loading FXML document with JavaFX API of version 16 by JavaFX runtime of version 8.0.121 Exception in Application start method java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389) at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767) Caused by: java.lang.RuntimeException: Exception in Application start method at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182) at java.lang.Thread.run(Thread.java:745) Caused by: javafx.fxml.LoadException: file:/C:/Users/15317/Desktop/code(1)/TomcatVuln-1.0-SNAPSHOT/TomcatVuln-1.0-SNAPSHOT.jar!/views/MainMenu.fxml
> 
> ```
>     at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
>     at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
>     at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
>     at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
>     at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
>     at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
>     at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
>     at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
>     at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
>     at org.dudu.TomcatVuln.TomcatAttackMain.start(TomcatAttackMain.java:17)
>     at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
>     at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
>     at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
>     at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
>     at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
>     at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
>     ... 1 more
> ```
> 
> Caused by: java.lang.RuntimeException: org.dom4j.DocumentException: 1 字节的 UTF-8 序列的字节 1 无效。 at org.dudu.TomcatVuln.view.MainMenuView.initialize(MainMenuView.java:249) at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548) ... 17 more Caused by: org.dom4j.DocumentException: 1 字节的 UTF-8 序列的字节 1 无效。 at org.dom4j.io.SAXReader.read(SAXReader.java:513) at org.dom4j.io.SAXReader.read(SAXReader.java:325) at org.dudu.TomcatVuln.utils.FileUtil.writeConfig(FileUtil.java:78) at org.dudu.TomcatVuln.view.MainMenuView.initialize(MainMenuView.java:233) ... 18 more Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 1 字节的 UTF-8 序列的字节 1 无效。 at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701) at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567) at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895) at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551) at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821) at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) at org.dom4j.io.SAXReader.read(SAXReader.java:494) ... 21 more Exception running application org.dudu.TomcatVuln.TomcatAttackMain

java8可以运行的，只不过你的运行目录可能存在中文，把中文目录换成英文目录后，再重新解压一下，
![image](https://github.com/errors11/TomcatVuln/assets/114721048/01400fdf-1467-4888-a9f8-ac8df745253b)
这几个路径不能有中文
