### ISSUE TITLE
师傅报错啊

### ISSUE THREAD

**Issue by mjznb666** [errors11/TomcatVuln#6]
四月 28, 2024 11:32:51 下午 javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 16 by JavaFX runtime of version 8.0.371
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:892)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:750)
Caused by: javafx.fxml.LoadException:
file:/D:/%e9%a2%98%e7%9b%ae/TomcatVuln-1.0-SNAPSHOT/TomcatVuln-1.0-SNAPSHOT/TomcatVuln-1.0-SNAPSHOT.jar!/views/MainMenu.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2606)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2584)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2446)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3249)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3210)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3183)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3159)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3139)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3132)
        at org.dudu.TomcatVuln.TomcatAttackMain.start(TomcatAttackMain.java:17)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        ... 1 more
Caused by: java.lang.RuntimeException: org.dom4j.DocumentException: Error on line 4 of document file:///D:/题目/TomcatVuln-1.0-SNAPSHOT/TomcatVuln-1.0-SNAPSHOT/config.xml : 2 字节的 UTF-8 序列的字节 2 无效。
        at org.dudu.TomcatVuln.view.MainMenuView.initialize(MainMenuView.java:249)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2553)
        ... 17 more
Caused by: org.dom4j.DocumentException: Error on line 4 of document file:///D:/题目/TomcatVuln-1.0-SNAPSHOT/TomcatVuln-1.0-SNAPSHOT/config.xml : 2 字节的 UTF-8 序列的字节 2 无效。
        at org.dom4j.io.SAXReader.read(SAXReader.java:511)
        at org.dom4j.io.SAXReader.read(SAXReader.java:325)
        at org.dudu.TomcatVuln.utils.FileUtil.writeConfigJsp(FileUtil.java:92)
        at org.dudu.TomcatVuln.view.MainMenuView.initialize(MainMenuView.java:234)
        ... 18 more
Caused by: org.xml.sax.SAXParseException; systemId: file:///D:/题目/TomcatVuln-1.0-SNAPSHOT/TomcatVuln-1.0-SNAPSHOT/config.xml; lineNumber: 4; columnNumber: 16; 2 字节的 UTF-8 序列的字节 2 无效。
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3156)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:113)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:644)
        at org.dom4j.io.SAXReader.read(SAXReader.java:494)
        ... 21 more
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 2 字节的 UTF-8 序列的字节 2 无效。
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:702)
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:373)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1689)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1365)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2823)
        ... 30 more
Exception running application org.dudu.TomcatVuln.TomcatAttackMain

**Comment by hunmeng123** [comment]
参考 issue 2

**Comment by 2270632741** [comment]
不能放在中文目录下
